server:
  port: 6999
spring:
  application:
    name: DEMO JS
  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect


  datasource:
    url: jdbc:h2:~/data/parserpalce;FILE_LOCK=SOCKET;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver




